### ISSUE TITLE
Version 1.1 Feature Implementations

### ISSUE THREAD

**Issue by whotooktwarden** [whotooktwarden/QuickGatewayKit#6]
Add the HTML5coin linux wallets (32-bit and 64-bit versions) into the package.  

Create a script which will create 500 HTML5coin public addresses and export the address list as JSON or CSV.  

Modify this script to fetch the 500 corresponding private keys and export them as either JSON or CSV.

Create a database setup script, this script must provide the following functionality when the user runs it:

Run sudo apt-get update && sudo apt-get upgrade followed by sudo apt-get install lamp

Create a MySQL Database with four total tables using the structure from mysql_setup.sh: public, private, redeem, and users. 

Primary key IDs auto increment as an integer and are not null. Foreign keys for  public_id and private_id both correlate to redeem_id, the intersection table.

Insert into public table the public keys and the private table into the private keys

Create redeem table, PK id auto increment int not_null, FK public and private_id. This is the intersection table for linking the public and private keys together.

Create users table: PK user_id ai int not_null, email not_null varchar60, ripple not_null varchar 60, fname not_null varchar60, lname not_null varchar60, FK public_id

Read either the exported JSON or CSV file for the public keys and import these keys into the public table.

Read either the exported JSON or CSV file for the private keys and import these keys into the private table.

For [Proposal: Version 1.1](https://github.com/whotooktwarden/QuickGatewayKit/wiki/Proposal:--Version-1.1,-Test-Default-Deposit-Option) to be closed, these features must be implemented to the master branch with a pull request into the release branch audited by a third party.

**Comment by whotooktwarden** [comment]
I'm going to start on the MySQL aspects of this issue.

**Comment by whotooktwarden** [comment]
Made headway on the MYSQL portion of this issue:

https://github.com/whotooktwarden/QuickGatewayKit/commit/45b9bfbddc51f01335548c6b871e81405755f09d - Still has syntax issues, raised an issue @ https://dba.stackexchange.com/questions/109098/weird-syntax-error

EDIT:  https://github.com/whotooktwarden/QuickGatewayKit/commit/6358eb6cc284c500ad697295f58a8575f1d74fb2 - Fixed this issue.

https://github.com/whotooktwarden/QuickGatewayKit/commit/90b55d0868532180b3df74f0103b058732b6a3f9 - The bash script which will perform the SQL above.

https://github.com/whotooktwarden/QuickGatewayKit/commit/454539eed78b13107d84b261c3eab33d5db4bc69 - The test script to ensure that the database's table structure is properly operating: inserts, selects, and deletes a test record.

**Comment by whotooktwarden** [comment]
https://github.com/whotooktwarden/QuickGatewayKit/commit/dcb4415ab45039137638257d93dc52120beb1ab6 closes this request.

**Comment by whotooktwarden** [comment]
Oops, wrong issue.

**Comment by xbrooks** [comment]
I've adjusted the link to our solution in the bountysource post but I don't think I can comment there.

The modules provided should provide the functionality you want and not just for html5coin but for hundreds of cryptocurrencies. :)

https://www.bountysource.com/issues/22277796-version-1-1-feature-implementations
https://github.com/RoastBeefSandwichCo/Roast-Coins/releases/tag/a94ab64

**Comment by whotooktwarden** [comment]
Much thanks to @ninobrooks for his support with expanding the QGK project's scope 100x more than initially planned!
