### ISSUE TITLE
Update README.md for Version 1.0.2

### ISSUE THREAD

**Issue by whotooktwarden** [whotooktwarden/QuickGatewayKit#9]
Edit the README.md file for spelling, grammar, and any incorrect or irrelevant information.  

Include instructions on how to edit the back-end for include.php to function.

Include instructions on how to operate the mysql_setup.sh script in preparation for Version 1.1.

**Comment by duckspeaker** [comment]
Slips self a five and looks in mirror. "Ya did good, kid. Ya did good."

**Comment by whotooktwarden** [comment]
@duckspeaker [I am seeking financial oversight and community developers](https://forum.ripple.com/viewtopic.php?f=1&t=10474) to avoid defamatory comments such as these appearing within this GitHub,

Please consider contacting me privately if you have an interest in this project.  I am already speaking to a lead developer with the HTML5coin wallet team and I have been contacted by an individual who is interested in producing tutorial videos for QGK over YouTube.  Last, this same individual has informed me that he knows of a few community Ripple developers who are aware of this project; we are in the process of setting up a round-table discussion via Google Hangouts.  A YouTube video may be recorded to provide more background information to the bountysource, github, and official Ripple forum communities about how this github will be maintained, the bountysource funds disbursed, and the development roadmap.

Please refrain from posting any more smart ass remarks within my project.  I treat the charity that Ripple Labs Inc has provided me with the utmost respect and due diligence  Thank you.

@julianeon  @RJTerrible  Regarding the peer reviews and financial oversight, this is _exactly_ why I had asked for your assistance..

**Comment by duckspeaker** [comment]
You know, I shouldn't have deleted my comment because now people are going to see your comment and think "My god, what horrible defamatory comment did @duckspeaker make?" So I'll leave it here for recordkeeping:

Slips self a five and looks in mirror. "Ya did good, kid. Ya did good."

**Comment by whotooktwarden** [comment]
https://github.com/whotooktwarden/QuickGatewayKit/commit/d7773b93321852679d2da1f636ba090e177f3ab8 closes this request.
